### ISSUE TITLE
fix uberspace repo

### ISSUE THREAD

**Issue by brutus** [Uberspace/docker-compile#1]
Currently our Uberspace RPM repository is not included / working:

```
[root@f6afcb14a6b9 /]# yum repolist
Loaded plugins: fastestmirror, ovl
Repository 'uberspace' is missing name in configuration, using id
Loading mirror speeds from cached hostfile
 * base: ftp.rrzn.uni-hannover.de
 * centos-sclo-rh: ftp.tu-chemnitz.de
 * centos-sclo-sclo: artfiles.org
 * epel: mirror.de.leaseweb.net
 * extras: artfiles.org
 * updates: mirror.netzwerge.de
repo id                                                                                    repo name                                                                                                          status
base/7/x86_64                                                                              CentOS-7 - Base                                                                                                    10070
centos-sclo-rh/x86_64                                                                      CentOS-7 - SCLo rh                                                                                                  6509
centos-sclo-sclo/x86_64                                                                    CentOS-7 - SCLo sclo                                                                                                 796
epel/x86_64                                                                                Extra Packages for Enterprise Linux 7 - x86_64                                                                     13311
extras/7/x86_64                                                                            CentOS-7 - Extras                                                                                                    397
updates/7/x86_64                                                                           CentOS-7 - Updates                                                                                                   735
repolist: 31818
```

Despite the following:

```dockerfile
RUN set -ex \
	&& yum install -y \
		centos-release-scl \
		epel-release \
	&& echo -e '[uberspace]\nbaseurl=https://repo.corona.uberspace.de/uberspace/$releasever/$basearch/\nenabled=0\ngpgcheck=0' > /etc/yum.repos.d/uberspace.repo \
```

The yum commands bail over this:

```
Repository 'uberspace' is missing name in configuration, using id
```

And the file seems to be ignored.

Instead of fixing the `echo` command, that writes the repo file, we could use:

```
yum-config-manager --add-repo https://repo.corona.uberspace.de/uberspace.repo
```

After that, the repo works - i.e. we can install packages from there (we might want to include a `yum makecache` anyway though).

**Comment by luto** [comment]
it doesn't bail afaik, that's just a warning because the repo really doesn't have a `name=`.

**Comment by luto** [comment]
I just checked again: this works fine in the CI that builds the packages. The repo is disabled, though, so you need to enable it beforehand. Maybe that's the problem?

**Comment by brutus** [comment]
Yes, it is just a warning, but I thought it leads to the repo being ignored. Because the line is so long and I didn't scroll far enough to read the `enabled=0` part, oh well…

Anyway, do we want it to not be enabled? Why do we include it?

I stumbled over this, because I was toying with the idea to include *Rust* by default (from our repo).

**Comment by luto** [comment]
Because I'd like to keep the finished packages far away from the build process within the CI. Otherwise I fear that I might end up installing the wrong one while testing due to a typo :sweat_smile:

**Comment by brutus** [comment]
Okay good call :+1: :smile: 

But how about enabling it, so we could install packages from our Repo during the Docker build process and disabling it afterwards?

Otherwise, yeah, we could just do that in the CI files for the projects… So feel free to close this, if you don't like it. Might not be worth the extra hassle, since we seldom use _Rust_, etc.

And - sorry if nitpicky - but maybe consider `yum-config-manager --add-repo https://repo.corona.uberspace.de/uberspace.repo && yum-config-manager --disable uberspace` or similar? Or not. I'm just not too fond of the `echo` thing, I guess, since we already got the repo files manged elsewhere. But never mind, no big deal.

**Comment by luto** [comment]
> But how about enabling it, so we could install packages from our Repo during the Docker build process and disabling it afterwards?

that runs into the same problem: we use this image to build those very packages.

> And - sorry if nitpicky - but maybe consider `yum-config-manager (...)` or similar?

yes, please!

**Comment by brutus** [comment]
Use case solved by internal CI features `$ENABLE_UBERSPACE_REPO` and `$YUM_DEPENDENCIES`… Added some PRs for cleanup.
